name = "events-scraper"
type = "webpack"
workers_dev = true
webpack_config = "webpack.config.js"
account_id = "ba8fecd59fd3205323517712ce3aedd7"
kv_namespaces = [ 
    { binding = "EVENTS_KV", id = "7abcd2d7ee2345f9bb627ce902b1af44", preview_id = "d63e8f5f69834447983f75b7887e3c38" }
]

[triggers]
    crons = ["00 08 * * *"]
